import type { Course } from "@/integrations/supabase/courses";

// Used when the courses table is empty or unreachable so the user never sees
// a "no courses available" state — recommendations and pricing still flow.
// These mirror the production seed in supabase/migrations/20260511180000.
export const FALLBACK_COURSES: Course[] = [
  {
    id: "f-bundle",
    slug: "complete-playbook",
    title: "The Complete Playbook",
    subtitle: "All 7 courses · Every stage covered · Lifetime access.",
    description: null,
    category: "bundle",
    level: "all",
    duration_hours: 30,
    module_count: 29,
    price_cents: 89900,
    original_price_cents: 159500,
    featured: true,
    position: 0,
    image_url: null,
    outcomes: [
      "Every module from every course",
      "Lifetime updates as tax law changes",
      "Priority email support",
      "All future courses included",
    ],
    who_for: [
      "Owners committed to the full system",
      "Anyone planning 3+ year growth",
      "CFOs, advisors, and operators",
    ],
    recommended_for: ["pre-llc", "new-owner", "growing", "scaling"],
    stripe_price_id: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "f-foundations",
    slug: "foundations-playbook",
    title: "The Foundations Playbook",
    subtitle: "Set up your business the right way from day one.",
    description: null,
    category: "foundations",
    level: "beginner",
    duration_hours: 4.5,
    module_count: 4,
    price_cents: 14900,
    original_price_cents: null,
    featured: true,
    position: 1,
    image_url: null,
    outcomes: [
      "Pick the right entity for your situation",
      "Set up an EIN, operating agreement, and books that scale",
      "Avoid the $5K+ setup mistakes most new owners make",
      "Lock in tax elections that save thousands year-one",
    ],
    who_for: ["Pre-LLC founders", "Owners in their first 6 months"],
    recommended_for: ["pre-llc", "new-owner"],
    stripe_price_id: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "f-scorp",
    slug: "scorp-strategy",
    title: "The S-Corp Strategy",
    subtitle: "Cut self-employment tax without crossing the IRS.",
    description: null,
    category: "tax",
    level: "intermediate",
    duration_hours: 3,
    module_count: 3,
    price_cents: 24900,
    original_price_cents: null,
    featured: true,
    position: 2,
    image_url: null,
    outcomes: [
      "Decide if an S-Corp election fits your numbers",
      "Calculate a defensible reasonable salary",
      "Set up the right payroll cadence",
    ],
    who_for: ["Solo owners netting $40K+", "LLCs ready to elect S-Corp"],
    recommended_for: ["new-owner", "growing"],
    stripe_price_id: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "f-tax-planning",
    slug: "year-round-tax-planning",
    title: "Year-Round Tax Planning",
    subtitle: "Plan during the year — not after it ends.",
    description: null,
    category: "tax",
    level: "intermediate",
    duration_hours: 5.5,
    module_count: 5,
    price_cents: 34900,
    original_price_cents: null,
    featured: true,
    position: 3,
    image_url: null,
    outcomes: [
      "Build a quarterly tax-planning rhythm",
      "Capture every legal deduction with documentation",
      "Stop being surprised by April",
    ],
    who_for: ["Owners with revenue $100K+"],
    recommended_for: ["new-owner", "growing", "scaling"],
    stripe_price_id: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "f-bookkeeping",
    slug: "bookkeeping-foundation",
    title: "Bookkeeping Foundation",
    subtitle: "Numbers you can actually use to make decisions.",
    description: null,
    category: "foundations",
    level: "beginner",
    duration_hours: 3.5,
    module_count: 4,
    price_cents: 9900,
    original_price_cents: null,
    featured: false,
    position: 4,
    image_url: null,
    outcomes: ["Separate business and personal cleanly", "Set up a chart of accounts that scales"],
    who_for: ["DIY owners on spreadsheets"],
    recommended_for: ["pre-llc", "new-owner", "growing"],
    stripe_price_id: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "f-payroll",
    slug: "payroll-contractors",
    title: "Payroll & Contractors Mastery",
    subtitle: "Hire the right way. Avoid five-figure penalties.",
    description: null,
    category: "operations",
    level: "intermediate",
    duration_hours: 4,
    module_count: 4,
    price_cents: 19900,
    original_price_cents: null,
    featured: false,
    position: 5,
    image_url: null,
    outcomes: [
      "Classify W-2 vs 1099 correctly",
      "Set up compliant payroll without breaking the bank",
    ],
    who_for: ["Owners hiring their first employee"],
    recommended_for: ["growing", "scaling"],
    stripe_price_id: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "f-protection",
    slug: "asset-protection-blueprint",
    title: "Asset Protection Blueprint",
    subtitle: "Separate operating risk from your personal wealth.",
    description: null,
    category: "protection",
    level: "advanced",
    duration_hours: 4.5,
    module_count: 4,
    price_cents: 29900,
    original_price_cents: null,
    featured: false,
    position: 6,
    image_url: null,
    outcomes: [
      "Structure holding companies and operating LLCs",
      "Protect personal assets from business liability",
    ],
    who_for: ["Owners with $250K+ in personal/business assets"],
    recommended_for: ["growing", "scaling"],
    stripe_price_id: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "f-exit",
    slug: "exit-planning",
    title: "Business Exit Planning",
    subtitle: "Structure today for a tax-efficient sale tomorrow.",
    description: null,
    category: "exit",
    level: "advanced",
    duration_hours: 5,
    module_count: 5,
    price_cents: 39900,
    original_price_cents: null,
    featured: false,
    position: 7,
    image_url: null,
    outcomes: [
      "Use QSBS §1202 to exclude up to $10M in gains",
      "Plan succession or sale years ahead",
    ],
    who_for: ["Owners thinking 3-10 years to exit"],
    recommended_for: ["scaling"],
    stripe_price_id: null,
    created_at: "",
    updated_at: "",
  },
];
